### ISSUE TITLE
Adapter startet nicht mit JS-Controller 6.0.1

### ISSUE THREAD

**Issue by LastPerfectTobi** [o0shojo0o/ioBroker.epson_ecotank_et_2750#413]
Nach Update vom JS-Controller auf 6.0.1 beta startet der Adapter v0.0.12 nicht mehr und es kommen folgende Fehler:

```
2024-06-11 09:34:31.112 - info: host.raspberrypi instance system.adapter.epson_ecotank_et_2750.0 started with pid 7450
2024-06-11 09:34:33.296 - error: host.raspberrypi Caught by controller[0]: /opt/iobroker/node_modules/iobroker.epson_ecotank_et_2750/main.js:31
2024-06-11 09:34:33.297 - error: host.raspberrypi Caught by controller[0]: adapter = new utils.Adapter(options);
2024-06-11 09:34:33.297 - error: host.raspberrypi Caught by controller[0]: ^
2024-06-11 09:34:33.297 - error: host.raspberrypi Caught by controller[0]: TypeError: utils.Adapter is not a constructor
2024-06-11 09:34:33.297 - error: host.raspberrypi Caught by controller[0]: at startAdapter (/opt/iobroker/node_modules/iobroker.epson_ecotank_et_2750/main.js:31:15)
2024-06-11 09:34:33.297 - error: host.raspberrypi Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.epson_ecotank_et_2750/main.js:278:5)
2024-06-11 09:34:33.297 - error: host.raspberrypi Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1364:14)
2024-06-11 09:34:33.298 - error: host.raspberrypi Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
2024-06-11 09:34:33.298 - error: host.raspberrypi Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1203:32)
2024-06-11 09:34:33.298 - error: host.raspberrypi Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1019:12)
2024-06-11 09:34:33.298 - error: host.raspberrypi Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
2024-06-11 09:34:33.298 - error: host.raspberrypi Caught by controller[0]: at node:internal/main/run_main_module:28:49
2024-06-11 09:34:33.298 - error: host.raspberrypi Caught by controller[0]: Node.js v18.20.3
2024-06-11 09:34:33.298 - error: host.raspberrypi instance system.adapter.epson_ecotank_et_2750.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-06-11 09:34:33.299 - info: host.raspberrypi Restart adapter system.adapter.epson_ecotank_et_2750.0 because enabled
2024-06-11 09:34:38.433 - info: host.raspberrypi "system.adapter.epson_ecotank_et_2750.0" disabled

```

**Comment by mcm1957** [comment]
@LastPerfectTobi 
Bitte die Version des Adapters angeben

@o0shojo0o 
Bitt @iobroker/adapetr-core auf aktuelle Version bringen und eine neue Release erstellen.

**Comment by mcm1957** [comment]
Unstale

**Comment by mcm1957** [comment]
Unstale

**Comment by mcm1957** [comment]
Unstale

**Comment by mcm1957** [comment]
mangels nachgefragter Informationen -> close
